- name: "Configure host"
  hosts: 127.0.0.1
  connection: local
  become: yes
  environment:
    HOST: "http://thumborize.me"
    THUMBOR_HOST: "http://thumbor.thumborize.me"
  tasks:
    - name: "Install git"
      apt:
        name: git
        state: latest
      tags: ["utils"]
    - name: "Install Python"
      apt:
        name: python3
        state: latest
      tags: ["utils"]
    - name: "Install Python PIP"
      apt:
        name: python3-pip
        state: latest
      tags: ["utils"]
    - name: "Install make"
      apt:
        name: make
        state: latest
      tags: ["utils"]
    - name: "Install libcurl"
      apt:
        name: libcurl4-openssl-dev
        state: latest
      tags: ["utils"]
    - name: "Install libssl"
      apt:
        name: libssl-dev
        state: latest
      tags: ["utils"]
    - name: "Install supervisor"
      apt:
        name: supervisor
        state: latest
      tags: ["utils"]
    - name: "Install gifsicle"
      apt:
        name: gifsicle
        state: latest
      tags: ["utils"]
    - name: "Install nginx"
      apt:
        name: nginx
        state: latest
      tags: ["utils"]
    - name: "Install redis"
      apt:
        name: redis-server
        state: latest
      tags: ["utils"]
    - name: "Install libgl1"
      apt:
        name: libgl1
        state: latest
      tags: ["utils"]
    - name: Create dir logs and permissions
      ansible.builtin.file:
         path: /var/logs/
         state: directory
         mode: '0756'
      tags: ["dir"]
    - name: Create dir run and permissions
      ansible.builtin.file:
         path: /var/logs/
         state: directory
         mode: '0756'
      tags: ["dir"]
    - name: Create dir logs and permissions
      ansible.builtin.file:
         path: /tmp/thumbor/
         state: directory
         mode: '0756'
      tags: ["dir"]
    - name: Create dir logs and permissions
      ansible.builtin.file:
         path: /tmp/current/
         state: directory
         mode: '0756'
      tags: ["dir"]
    - name: Download Git Thumbor
      ansible.builtin.git:
         repo: https://github.com/thumbor/thumborizeme.git
         dest: /tmp/current/
         force: yes
         version: thumborizeme-gcp
      tags: ["thumbor"]
    - name: Run make 'setup'
      make:
        chdir: /tmp/current
        target: setup
      tags: ["thumbor"]
    - name: Copy supervisord.conf and permissions
      ansible.builtin.copy:
        src: /tmp/current/supervisor.conf
        dest: /etc/supervisor/supervisord.conf
        mode: '0756'
      tags: ["thumbor"]
    - name: Copy thumbor.conf and permissions
      ansible.builtin.copy:
        src: /tmp/current/thumbor.conf
        dest: /etc/thumbor.conf
        mode: '0756'
      tags: ["thumbor"]
    - name: Copy nginx.conf and permissions
      ansible.builtin.copy:
        src: /tmp/current/nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0756'
      tags: ["thumbor"]
    - name: "Restart nginx"
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
      tags: ["restarted"]
    - name: "Restart supervisor"
      ansible.builtin.systemd:
        state: restarted
        name: supervisor
        enabled: yes
      tags: ["restarted"]
